default: &default
  adapter: postgresql
  encoding: utf8
  collate: pt_BR.UTF-8
  ctype: pt_BR.UTF-8
  host: host
  username: username
  password: password
  timeout: 5000

development:
  <<: *default
  database: codero_dev

test:
  <<: *default
  database: codero_test

production:
  <<: *default
  database: codero
